### ISSUE TITLE
Visualization error on prefixes slide

### ISSUE THREAD

**Issue by montogeek** [nodesource/understanding-npm#1]
Hi!

Great visualization! I found an issue in the prefixes slide, the graphs of the last column are in the next row, look:
![understanding-npm](https://cloud.githubusercontent.com/assets/1002461/8213314/a24d6686-14e6-11e5-91b4-de51c6a5926f.png)

I'm using Chrome 44.0.2403.39 on Mac OS X Yosemite

**Comment by hughsk** [comment]
This is a weird one – looking into it :)

**Comment by hughsk** [comment]
Thanks for the report @montogeek, should be fixed on the next deploy!
