### ISSUE TITLE
Selector error in (Chrome 43, Ubuntu 14.04)

### ISSUE THREAD

**Issue by Calvein** [nodesource/understanding-npm#5]
I have this error:

```
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '[name ="tweak-x"]' is not a valid selector.
https://marketing.nodesource.com/acton/bn/15680?ref=https%3A%2F%2Ft.co%2FRtUiySz74C&v=2&ts=1434600044844&nc=0 Failed to load resource: net::ERR_INSECURE_RESPONSE
```

So I tried to run `document.querySelector('[name ="tweak-x"]')` and I have a similar error while `document.querySelector('[name="tweak-x"]')` (no space before the `=`) work fine.

![image](https://cloud.githubusercontent.com/assets/243189/8223964/7ab7fc8a-15c2-11e5-9c28-3345fa9e4c32.png)

**Comment by Qard** [comment]
Same issue here.

**Comment by jbilcke** [comment]
I get a network issue `net::ERR_INSECURE_RESPONSE` when the following ressource is called:
```
GET https://marketing.nodesource.com/acton/bn/15680?ref=&v=2&ts=1435043632952&nc=0

```

then just right after:
```
bundle.js:8 Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '[name ="tweak-x"]' is not a valid selector.
```

**Comment by bierik** [comment]
:+1: same issue

**Comment by pbakondy** [comment]
Same issue with Chrome 43 on Mac
